### ISSUE TITLE
changeg

### ISSUE THREAD

**Issue by YeQiuYq** [TravellerXi/OpenVpnWithWebControl#2]
修改密码显示注册成功。。。。
显示bug
![QQ图片20191203200453](https://user-images.githubusercontent.com/58458818/70049698-40be8a80-1608-11ea-801b-e17c1078e3a5.png)
修改邀请码，显示404
![image](https://user-images.githubusercontent.com/58458818/70049807-7fecdb80-1608-11ea-86f3-9e65b387f2e5.png)

**Comment by TravellerXi** [comment]
![image](https://user-images.githubusercontent.com/51471579/70058482-f2b28280-1619-11ea-865f-ff93b65e3888.png)
第一个问题是代码复用未审查仔细，已修复。
第二个问题与用户沟通，系用户自己问题。
